#!/usr/bin/env node
/*
 * Encrypt the extracted dashboard data so the static site can be password
 * protected. Reads the plaintext src/data/data.json and writes an encrypted
 * assets/js/data.enc.js payload that the browser decrypts with Web Crypto
 * once the correct password is entered.
 *
 * Crypto: PBKDF2(SHA-256) key derivation -> AES-256-GCM. The output ciphertext
 * has the 16-byte GCM auth tag appended (ct || tag), which is exactly the
 * layout the browser's crypto.subtle.decrypt() expects.
 *
 * Usage:
 *   node scripts/encrypt_data.js                 # uses the default password
 *   PRIMELAZE_PW='your-password' node scripts/encrypt_data.js
 *
 * Only the ENCRYPTED file (assets/js/data.enc.js) is served by the website;
 * the plaintext data.json / source workbooks are never published (see the
 * Pages workflow).
 */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.resolve(__dirname, "..");
const IN = path.join(ROOT, "src", "data", "data.json");
const OUT = path.join(ROOT, "assets", "js", "data.enc.js");

const PASSWORD = process.env.PRIMELAZE_PW || "prime@1986";
const ITER = 200000;
const KEYLEN = 32; // AES-256

function main() {
  const plaintext = fs.readFileSync(IN); // Buffer of the JSON bytes

  const salt = crypto.randomBytes(16);
  const iv = crypto.randomBytes(12);
  const key = crypto.pbkdf2Sync(PASSWORD, salt, ITER, KEYLEN, "sha256");

  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
  const ct = Buffer.concat([cipher.update(plaintext), cipher.final()]);
  const tag = cipher.getAuthTag(); // 16 bytes
  const payload = Buffer.concat([ct, tag]); // ct || tag  (Web Crypto layout)

  const enc = {
    v: 1,
    kdf: "PBKDF2",
    hash: "SHA-256",
    iter: ITER,
    salt: salt.toString("base64"),
    iv: iv.toString("base64"),
    ct: payload.toString("base64"),
  };

  const banner =
    "// AUTO-GENERATED by scripts/encrypt_data.js — encrypted dashboard data.\n" +
    "// Decrypted in-browser with the site password. Do not edit by hand.\n";
  fs.writeFileSync(OUT, banner + "window.APP_DATA_ENC = " + JSON.stringify(enc) + ";\n");

  console.log("Encrypted", plaintext.length, "bytes ->", path.relative(ROOT, OUT));
  console.log("  iterations:", ITER, "| salt/iv/tag: random per run");
  console.log("  password source:", process.env.PRIMELAZE_PW ? "PRIMELAZE_PW env" : "default");
}

main();
